In [1]:
## install numpy libary
!pip install numpy

In [2]:
import numpy as np

## Why we are learning numpy:
    - allows for vectorised operation
    - it is written is C

In [6]:
## Proof that numpy is much much efficient than normal list

# todo: 

import time

start = time.time()
my_list = list(range(1, 1_00_000_000)) # this will be very slow
transformed_list = [x*2 for x in my_list] # this will be very very slow
time_taken_list = time.time() - start
print("Time taken in list:", time_taken_list)

start = time.time()
my_array = np.array(my_list)  # this will take a lot of time
transformed_array = my_array *  # this will be very fast
time_taken_array = time.time() - start
print("Time taken in array:", time_taken_array)

Time taken in list: 10.59260892868042
Time taken in array: 10.046459913253784


In [9]:
## Proof that numpy is much much efficient than normal list

# todo: 

import time

my_list = list(range(1, 1_00_000_000)) # this will be very slow
start = time.time()
transformed_list = [x*2 for x in my_list] # this will be very very slow
time_taken_list = time.time() - start
print("Time taken in list:", time_taken_list)

my_array = np.array(my_list)  # this will take a lot of time
start = time.time()
transformed_array = my_array * 2  # this will be very fast
time_taken_array = time.time() - start
print("Time taken in array:", time_taken_array)

# Results:
# Time taken in list: 10.62601900100708
# Time taken in array: 0.6167585849761963

Time taken in list: 10.62601900100708
Time taken in array: 0.6167585849761963


In [7]:
import time
# Python list — slow loop-based
python_list = list(range(1_000_000_00))
start = time.time()
result = [x * 2 for x in python_list]
print(f"List: {time.time() - start:.4f}s")

# NumPy array — vectorized C operations
np_array = np.arange(1_000_000_00)
start = time.time()
result = np_array * 2
print(f"NumPy: {time.time() - start:.4f}s")

List: 4.6223s
NumPy: 2.1538s


In [10]:
# len(my_array)

In [89]:
%%time


Time taken in array: 9.543986797332764
CPU times: user 2.72 s, sys: 2.64 s, total: 5.36 s
Wall time: 9.54 s


In [3]:
time.time()

1773549562.58636

# Creating numpy arrays

In [7]:
x = [1, 2, 3, 4]  # python list ( hetrogenous)
y = [1, 2.5, 3, "apple"] # allowed in a list
x

[1, 2, 3, 4]

In [6]:
# create a numpy array from a list

my_array = np.array([1, 2, 3, 4])
my_array

array([1, 2, 3, 4])

In [8]:
type(my_array)

numpy.ndarray

In [10]:
nested_list = [[1, 2, 3], [4, 5, 6]]


my_array = np.array([[1, 2, 3], 
          [4, 5, 6]])

print(nested_list)
my_array

[[1, 2, 3], [4, 5, 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# print(dir(my_array))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [15]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
my_array.ndim

2

## some common properties of arrays

In [17]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
my_array.shape ## (2, 3) --> there are two rows and 3 columns

(2, 3)

In [21]:
another_array = np.array([[3,  4, 5, 6], 
                          [5,  6, 7, 8], 
                          [10, 20, 30, 40]
                         ])

another_array.shape

(3, 4)

In [22]:
another_array.ndim

2

In [ ]:
# 3d arrays

# todo: example of 3d or 4d arrays



In [26]:
print(another_array)
another_array.size

[[ 3  4  5  6]
 [ 5  6  7  8]
 [10 20 30 40]]


12

In [27]:
another_array.dtype

dtype('int64')

In [28]:
float_array = np.array([ [1, 2, 3], [10, 20, 50.5]])
float_array

array([[ 1. ,  2. ,  3. ],
       [10. , 20. , 50.5]])

In [29]:
float_array.dtype

dtype('float64')

In [31]:
print(another_array)
another_array.itemsize

[[ 3  4  5  6]
 [ 5  6  7  8]
 [10 20 30 40]]


8

## Datatypes in numpy array

In [11]:
x = np.array([1, 2, 3, 4.5])
x

array([1. , 2. , 3. , 4.5])

In [12]:
x = np.array([1, 2, 3, 4.5], dtype = np.int32)
x

array([1, 2, 3, 4], dtype=int32)

In [13]:
x.itemsize

4

In [40]:
## todo: np.int8, np.int32, float32, float64

x = np.array([1, 2, 3, 4.5], dtype = np.int64)
x

array([1, 2, 3, 4])

In [41]:
x.itemsize

8

In [42]:
x = np.array([1, 2, 3, 4.5])
x

array([1. , 2. , 3. , 4.5])

# Indexing and Slicing in numpy arrays

In [15]:
marks_list = [10, 20, 30, 40, 50]

type(marks_list[-1]) ## access the value using a index

int

In [16]:
marks_array = np.array(marks_list)
marks_array # 1 dimensional

array([10, 20, 30, 40, 50])

In [17]:
## access elements from marks_array
type(marks_array[0])

numpy.int64

In [18]:
print(marks_array[0]) ## this will giev the first
print(marks_array[-1]) ## give the last value

10
50


In [25]:
## slicing ( array[start : stop : step])
marks_list = [10, 20, 30, 40, 50]
print(marks_array)
marks_array[0:4]


[10 20 30 40 50]


array([10, 20, 30, 40])

In [24]:
marks_array[::2] # get the entire array but skip alternate values

array([10, 30, 50])

In [20]:
marks_array.shape[0]

5

In [21]:
marks_array.shape

(5,)

In [65]:
marks_array[:]

array([10, 20, 30, 40, 50])

In [66]:
marks_array[ 2 : ]

array([30, 40, 50])

In [67]:
marks_array[  : 4]

array([10, 20, 30, 40])

## Working with 2D arrays 

In [72]:
y = np.array( [[1, 2, 3], [10, 20, 30]])
y

array([[ 1,  2,  3],
       [10, 20, 30]])

In [74]:
y

array([[ 1,  2,  3],
       [10, 20, 30]])

In [75]:
y[1, 1]

np.int64(20)

In [26]:
y = np.array( [[1, 2, 3], 
               [11, 22, 33], 
               [24, 48, 96], 
               [10, 20, 30]])
y

array([[ 1,  2,  3],
       [11, 22, 33],
       [24, 48, 96],
       [10, 20, 30]])

In [ ]:
y[0]## will return the first row

In [31]:
y[0,  1 : 3] 

array([2, 3])

In [32]:
y[1:3, 1:3]

array([[22, 33],
       [48, 96]])

In [77]:
y[2, 2]

np.int64(96)

In [85]:
y[1:3 , 0]

array([11, 24])

In [82]:
# slicing

y[2 , 1:]

array([48, 96])

In [80]:
y[0 , :]

array([1, 2, 3])

In [81]:
y[1, :]

array([11, 22, 33])

# More about indexing

In [91]:
a = np.array([11, 232, 53, 24, 95])

ind = [2, 4]
# a[[2, 4]]
a[ind]

array([53, 95])

## modifying the arrays

In [93]:
a = np.array([11, 232, 53, 24, 95])

a[0]  = 33

In [94]:
a

array([ 33, 232,  53,  24,  95])

In [95]:
ind = [1, 3]
a[ind] = 0

In [96]:
a

array([33,  0, 53,  0, 95])

## appending and removing elements

In [99]:
x = np.array([ 1, 2, 3, 4, 5])
np.append(x, 100)

array([  1,   2,   3,   4,   5, 100])

In [101]:
y = np.append(x, 5000)  # not in-place operation

In [104]:
x

array([1, 2, 3, 4, 5])

In [108]:
np.append(x, [[100,200, 300], [500, 600, 700]])

array([  1,   2,   3,   4,   5, 100, 200, 300, 500, 600, 700])

In [112]:
x = np.array([[1, 2, 3], [4, 5, 6], [9, 10, 11]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]]


In [113]:
np.append(x, [20, 30, 40, 50, 60, 70])

array([ 1,  2,  3,  4,  5,  6,  9, 10, 11, 20, 30, 40, 50, 60, 70])

In [116]:
x = np.array([[1, 2, 3], [4, 5, 6], [9, 10, 11]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [123]:
np.append(x, np.array([[100, 200, 300]]) , axis = 0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  9,  10,  11],
       [100, 200, 300]])

In [ ]:
np.append(x, np.array([[100, 200, 300]]) , axis = 0)

In [125]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [124]:
np.append(x, np.array([[100, 200, 300]]))

array([  1,   2,   3,   4,   5,   6,   9,  10,  11, 100, 200, 300])

In [127]:
x.shape

(3, 3)

In [128]:
y= np.append(x, np.array([[100, 200, 300]]) , axis= 0 )

In [129]:
y.shape

(4, 3)

In [ ]:
np.insert()

In [130]:
x = np.array([[1, 2, 3], [40, 50, 60]])

val = np.array([[100, 200, 300], [400, 500, 600]])
np.append(x, val)

array([  1,   2,   3,  40,  50,  60, 100, 200, 300, 400, 500, 600])

In [133]:
x = np.array([[1, 2, 3], [40, 50, 60]])

val = np.array([[100, 200, 300], [400, 500, 600]] )
np.append(x, val, axis = 0)

array([[  1,   2,   3],
       [ 40,  50,  60],
       [100, 200, 300],
       [400, 500, 600]])

In [40]:
# sir suppose we have 
x= np.array([10,20,30,40]) # 1d array
y = np.array([[10,20,30,40]]) # 2d array

z = np.array([[[10,20,30,40]]])
print(y.ndim)
print(y.shape)
print(z.shape)

# row number = 1
# col number = 4
# is it right

2
(1, 4)
(1, 1, 4)


In [134]:
x = np.array([[1, 2, 3], 
              [40, 50, 60]])

val = np.array([[100, 200, 300], 
                [400, 500, 600]] )
np.append(x, val, axis = 1)

array([[  1,   2,   3, 100, 200, 300],
       [ 40,  50,  60, 400, 500, 600]])

In [ ]:
np.insert(arr, obj, values, axis=None)

In [136]:
x = np.array([[1, 2, 3], 
              [40, 50, 60]])

np.insert(x , [2], [[1000], [2000]], axis =1)

array([[   1,    2, 1000,    3],
       [  40,   50, 2000,   60]])

In [140]:
x = np.array([[1, 2, 3], 
              [40, 50, 60], 
             [11, 33, 44]])

np.insert(x , [1], [[1000, 2000, 3000]], axis =0)

array([[   1,    2,    3],
       [1000, 2000, 3000],
       [  40,   50,   60],
       [  11,   33,   44]])

# flattening a array

In [41]:
# how to flatten a array
# todo: 

x = np.array([[1, 2, 3], 
              [40, 50, 60], 
             [11, 33, 44]])

x.flatten()




array([ 1,  2,  3, 40, 50, 60, 11, 33, 44])

In [47]:
x.size

9

In [49]:
x.shape

(3, 3)

In [52]:
x.resize(1, 9) # inplace operation
x

array([[ 1,  2,  3, 40, 50, 60, 11, 33, 44]])

In [51]:
x.resize(9, 1)
x

array([[ 1],
       [ 2],
       [ 3],
       [40],
       [50],
       [60],
       [11],
       [33],
       [44]])

In [56]:
# not inplace operation
x.reshape(9, 1) # returning another array with the elements in the desired shape

array([[ 1],
       [ 2],
       [ 3],
       [40],
       [50],
       [60],
       [11],
       [33],
       [44]])

In [57]:
x

array([[ 1,  2,  3, 40, 50, 60, 11, 33, 44]])

In [ ]:
my_list = [1, 2, 3] # list

my_array= np.array([1, 2, 3]) ## array



In [58]:
# np.newaxis

# todo: add new axis to the array

x = np.array([[1, 2, 3], 
              [40, 50, 60], 
             [11, 33, 44]])



array([[ 1,  2,  3, 40, 50, 60, 11, 33, 44]])

# broadcasting
    - scalars are stretched to match the array shape and mathematical operations are applied
    - 

In [147]:
x = np.array([1, 2, 3, 4, 5])


x = np.array([[1, 2, 3, 4, 5], [10, 20, 40, 50, 60]])


x + 10 ## scalar broadcasting

array([[11, 12, 13, 14, 15],
       [20, 30, 50, 60, 70]])

In [148]:
x * 10

array([[ 10,  20,  30,  40,  50],
       [100, 200, 400, 500, 600]])

In [149]:
x ** 2

array([[   1,    4,    9,   16,   25],
       [ 100,  400, 1600, 2500, 3600]])

In [150]:
0 - x

array([[ -1,  -2,  -3,  -4,  -5],
       [-10, -20, -40, -50, -60]])

In [151]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[11, 22, 33], [44, 55, 66]])

x + y

array([[12, 24, 36],
       [48, 60, 72]])

In [156]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[10, 20, 30]])
# z = 10

x + y

array([[11, 22, 33],
       [14, 25, 36]])

In [158]:
d = np.array([[100], [200]])
e = np.array([2000])

d + e

array([[2100],
       [2200]])

# Boolean operations masking and filtering in numpy

In [160]:
marks = np.array(([50, 60, 70, 100, 40, 20 ]))

ind = [1, 3, 5]


# marks[[1, 3, 5]] ## another way to index from an array
marks[ind]

array([ 60, 100,  20])

In [168]:
marks = np.array(([50, 60, 70]))

ind = marks >=60
print(ind)
# ind = [True, False, True] ## mask
marks[ind]  # filtered result

[False  True  True]


array([60, 70])

In [169]:
marks = np.array(([50, 60, 70, 100, 40, 20 ]))
mask = marks > 60

marks[mask]

array([ 70, 100])

In [175]:
# given a list of numbers filter out the even numbers
nums = np.array(([54, 62, 79, 105, 40, 201 ]))

# mask = nums % 2 == 0
# nums[mask]


nums[ nums%2 == 0 ]

array([54, 62, 40])

In [177]:
nums = np.array(([[54, 62, 79], 
                 [105, 40, 201 ]]))

# mask = nums % 2 == 0
# nums[mask]


nums[ nums % 2 == 0 ]

array([54, 62, 40])

# argmin and argmax

In [178]:
nums = np.array(([54, 62, 79, 105, 40, 201 ]))

In [180]:
np.min(nums)  # what is the minimum number

np.int64(40)

In [181]:
np.max(nums)

np.int64(201)

In [184]:
np.argmin(nums)# where is the minimum number

np.int64(4)

In [185]:
np.argsort(nums) ## indices of the values in sorted order

array([4, 0, 1, 2, 3, 5])

In [186]:
nums[np.argsort(nums)]

array([ 40,  54,  62,  79, 105, 201])

In [183]:
np.sqrt(nums), np.log10(nums)

(array([ 7.34846923,  7.87400787,  8.88819442, 10.24695077,  6.32455532,
        14.17744688]),
 array([1.73239376, 1.79239169, 1.89762709, 2.0211893 , 1.60205999,
        2.30319606]))

# np.where --> important concept

In [188]:
nums = np.array(([54, 62, 79, 105, 40, 201 ]))


# we are proving only the condition
np.where( nums %2 == 0 )  # one way of using the np.where

(array([0, 1, 4]),)

In [189]:
# we are providing the condition and the values to take when condition is true and when conditon is false 


'''

condition  is nums %2 == 0

where condition is true it will take the value from 100
where condition is false it will take the values from nums

'''

np.where( nums %2 == 0, 100, nums)

array([100, 100,  79, 105, 100, 201])

In [191]:
nums = np.array(([54, 62, 79, 105, 40, 201 ]))
backup = np.array(([-100, -362, -379, -405, -340, -901 ]))
backup2 = backup*10000

'''
where the condition is true take the value from backup
where the condition is false take the value from nums

'''
np.where( nums %2 == 0, backup, nums)


array([-100, -362,   79,  105, -340,  201])

In [192]:
nums = np.array  (([ 54,  62,   79,   105,   40,  201 ]))
backup = np.array(([-100, -362, -379, -405, -340, -901 ]))
backup2 = backup*10000

'''
where the condition is true take the value from backup
where the condition is false take the value from backup

'''
np.where( nums %2 == 0, backup, backup2)

array([    -100,     -362, -3790000, -4050000,     -340, -9010000])

# 'reshape', 'resize'

# arange, linspace, zeros and ones

In [61]:
np.arange(0, 100, 4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [63]:
np.linspace(1, 10, 2) # two numbers linearly spaced between 1, 10

array([ 1., 10.])

In [73]:
## generate 50 numbers between 1 and 100

np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [74]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
np.ones((3, 6), dtype = np.float64)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# mathematical functions in numpy

In [81]:
np.sum([1, 2, 3])

np.int64(6)

In [82]:
np.prod([1, 2, 3])

np.int64(6)

In [83]:
np.cumprod([2, 3, 4, 5, 6])

array([  2,   6,  24, 120, 720])

In [84]:
np.cumsum([2, 3, 4, 5, 6])

array([ 2,  5,  9, 14, 20])

# basic statistical functions in numpy

In [85]:
np.min([1,  2, 3])

np.int64(1)

In [86]:
np.std([2, 3, 4], )

np.float64(0.816496580927726)

In [87]:
np.var([2, 3, 4], )

np.float64(0.6666666666666666)